### API CATEGORIA - GET
GET http://localhost:8080/api/v1/categorias

### API CATEGORIA - POST
POST http://localhost:8080/api/v1/categorias
Content-Type: application/json

{
    "id": 0,
    "nome": "Saldo Total"
}

### API CATEGORIA - PUT
PUT http://localhost:8080/api/v1/categorias/1
Content-Type: application/json

{
    "id": 1,
    "nome": "Saldo Atualizado"
}

### API CATEGORIA - DELETE
DELETE http://localhost:8080/api/v1/categorias/1