### API RELATÓRIO - GET
GET http://localhost:8080/api/v1/relatorios

### API RELATÓRIO - POST
POST http://localhost:8080/api/v1/relatorios
Content-Type: application/json

{
    "id": 0,
    "saldoTotal": 1000.00,
    "saldoPorCategoria": {
        "Receitas": 1500.00,
        "Despesas": 500.00
    },
    "simulacao": {
        "id": 1
    }
}

### API RELATÓRIO - PUT
PUT http://localhost:8080/api/v1/relatorios/1
Content-Type: application/json

{
    "id": 1,
    "saldoTotal": 1200.00,
    "saldoPorCategoria": {
        "Receitas": 1700.00,
        "Despesas": 500.00
    },
    "simulacao": {
        "id": 1
    }
}

### API RELATÓRIO - DELETE
DELETE http://localhost:8080/api/v1/relatorios/1